/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.UsuariosNsg;
import dao.Usuarios_DAO_Nsg;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;

/**
 *
 * @author u09229145165
 */
public class JDlgUsuariosNsg extends javax.swing.JDialog {
    private boolean incluindo;
    public UsuariosNsg usuariosNsg;
    public Usuarios_DAO_Nsg usuarios_DAO_Nsg;
    private MaskFormatter mascaraCPF, mascaraNascimento;

    /**
     * Creates new form JDlgUsuariosNsg
     */
    public JDlgUsuariosNsg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Usuarios_DAO_Nsg usuarios_DAO_Nsg = new Usuarios_DAO_Nsg();
        setTitle("Usuários");
        setLocationRelativeTo(null);
        Util.habilitar(false, jBtnExcluir_Nsg, jBtnAlterar_Nsg, jBtnConfirmar_Nsg, jBtnCancelar_Nsg, jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtApelido_Nsg, jFmtCpf_Nsg, jFmtNascimento_Nsg, jCboNivel_Nsg, jChbAtivo_Nsg, jPswSenha_Nsg);
        Util.habilitar(true, jBtnIncluir_Nsg, jBtnPesquisar_Nsg);
        Util.limparCampos(jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtApelido_Nsg, jFmtCpf_Nsg, jFmtNascimento_Nsg, jCboNivel_Nsg, jChbAtivo_Nsg, jPswSenha_Nsg);
    
        try {
            mascaraCPF = new MaskFormatter("###.###.###-##");
            mascaraNascimento = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            Logger.getLogger(JDlgUsuariosNsg.class.getName()).log(Level.SEVERE, null, ex);
        }
          
         jFmtCpf_Nsg.setFormatterFactory(new DefaultFormatterFactory(mascaraCPF));
         jFmtNascimento_Nsg.setFormatterFactory(new DefaultFormatterFactory(mascaraNascimento));
         
    }
        public UsuariosNsg viewBean() {
        UsuariosNsg usuariosNsg = new UsuariosNsg();
       
        usuariosNsg.setIdUsuariosNsg(Util.strInt(jTxtCodigo_Nsg.getText()));
        usuariosNsg.setNomeNsg(jTxtNome_Nsg.getText());
        usuariosNsg.setApelidoNsg(jTxtApelido_Nsg.getText());
        usuariosNsg.setCpfNsg(jFmtCpf_Nsg.getText());
       
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        try {
            usuariosNsg.setNascimentoNsg (formato.parse(jFmtNascimento_Nsg.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(JDlgClienteNsg.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        usuariosNsg.setNivelNsg(jCboNivel_Nsg.getSelectedIndex());
        usuariosNsg.setAtivoNsg( jChbAtivo_Nsg.isSelected() == true ? "S" : "N");
        usuariosNsg.setSenhaNsg(jPswSenha_Nsg.getText());
        
        return usuariosNsg;
       
    }
    
    public void beanView(UsuariosNsg usuariosNsg) {
        String id = String.valueOf(usuariosNsg.getIdUsuariosNsg());
       
        jTxtCodigo_Nsg.setText(id);
        jTxtNome_Nsg.setText(usuariosNsg.getNomeNsg());
        jTxtApelido_Nsg.setText(usuariosNsg.getApelidoNsg());
        jFmtCpf_Nsg.setText(usuariosNsg.getCpfNsg());
        
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        jFmtNascimento_Nsg.setText(formato.format(usuariosNsg.getNascimentoNsg()));
        
        jCboNivel_Nsg.setSelectedIndex(usuariosNsg.getNivelNsg());
        
        if (usuariosNsg.getAtivoNsg().equals("S") == true) {
            jChbAtivo_Nsg.setSelected(true);
        } else {
            jChbAtivo_Nsg.setSelected(false);
        }
        
        jPswSenha_Nsg.setText(usuariosNsg.getSenhaNsg());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jBtnExcluir_Nsg = new javax.swing.JButton();
        jFmtCpf_Nsg = new javax.swing.JFormattedTextField();
        jBtnConfirmar_Nsg = new javax.swing.JButton();
        jFmtNascimento_Nsg = new javax.swing.JFormattedTextField();
        jBtnCancelar_Nsg = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jBtnPesquisar_Nsg = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jBtnIncluir_Nsg = new javax.swing.JButton();
        jCboNivel_Nsg = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jChbAtivo_Nsg = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jPswSenha_Nsg = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jBtnAlterar_Nsg = new javax.swing.JButton();
        jTxtCodigo_Nsg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtNome_Nsg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtApelido_Nsg = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setText("CPF");

        jBtnExcluir_Nsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/02 - excluir.png"))); // NOI18N
        jBtnExcluir_Nsg.setText("Excluir");
        jBtnExcluir_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluir_NsgActionPerformed(evt);
            }
        });

        jFmtCpf_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtCpf_NsgActionPerformed(evt);
            }
        });

        jBtnConfirmar_Nsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/07 - confirmar.png"))); // NOI18N
        jBtnConfirmar_Nsg.setText("Confirmar");
        jBtnConfirmar_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmar_NsgActionPerformed(evt);
            }
        });

        jFmtNascimento_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtNascimento_NsgActionPerformed(evt);
            }
        });

        jBtnCancelar_Nsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/03 - exit.png"))); // NOI18N
        jBtnCancelar_Nsg.setText("Cancelar");
        jBtnCancelar_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelar_NsgActionPerformed(evt);
            }
        });

        jLabel7.setText("Nascimento");

        jBtnPesquisar_Nsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/06 - pesquisar.png"))); // NOI18N
        jBtnPesquisar_Nsg.setText("Pesquisar");
        jBtnPesquisar_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisar_NsgActionPerformed(evt);
            }
        });

        jLabel6.setText("Nível");

        jBtnIncluir_Nsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/04 - incluir.png"))); // NOI18N
        jBtnIncluir_Nsg.setText("Incluir");
        jBtnIncluir_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluir_NsgActionPerformed(evt);
            }
        });

        jCboNivel_Nsg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolher nível", "Baixo", "Médio", "Alto" }));
        jCboNivel_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboNivel_NsgActionPerformed(evt);
            }
        });

        jLabel8.setText("Ativo");

        jChbAtivo_Nsg.setText("Sim");
        jChbAtivo_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChbAtivo_NsgActionPerformed(evt);
            }
        });

        jLabel9.setText("Senha");

        jLabel2.setText("Código");

        jBtnAlterar_Nsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/01 - alterar.png"))); // NOI18N
        jBtnAlterar_Nsg.setText("Alerar");
        jBtnAlterar_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterar_NsgActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome");

        jLabel4.setText("Apelido");

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/08 - usuario.png"))); // NOI18N
        jLabel10.setText("Cadastrar Usuários");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtnIncluir_Nsg)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnAlterar_Nsg))
                                    .addComponent(jBtnConfirmar_Nsg))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtnExcluir_Nsg)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnPesquisar_Nsg))
                                    .addComponent(jBtnCancelar_Nsg))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jCboNivel_Nsg, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jFmtCpf_Nsg, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTxtNome_Nsg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTxtApelido_Nsg)
                                                .addComponent(jLabel4)
                                                .addComponent(jFmtNascimento_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jChbAtivo_Nsg))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jPswSenha_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(jLabel2)
                                    .addComponent(jTxtCodigo_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtCodigo_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtNome_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtApelido_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFmtCpf_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtNascimento_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCboNivel_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jChbAtivo_Nsg)
                            .addComponent(jPswSenha_Nsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAlterar_Nsg)
                    .addComponent(jBtnExcluir_Nsg)
                    .addComponent(jBtnIncluir_Nsg)
                    .addComponent(jBtnPesquisar_Nsg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCancelar_Nsg)
                    .addComponent(jBtnConfirmar_Nsg))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnExcluir_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluir_NsgActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jBtnConfirmar_Nsg, jBtnCancelar_Nsg, jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtApelido_Nsg, jFmtCpf_Nsg, jFmtNascimento_Nsg, jCboNivel_Nsg, jChbAtivo_Nsg, jPswSenha_Nsg);
        Util.habilitar(true, jBtnIncluir_Nsg, jBtnAlterar_Nsg, jBtnPesquisar_Nsg, jBtnExcluir_Nsg);
        
        if (Util.perguntar("Deseja excluir o projeto?") == true){
            UsuariosNsg usuariosNsg = viewBean();
            Usuarios_DAO_Nsg usuarios_DAO_Nsg = new Usuarios_DAO_Nsg();
            usuarios_DAO_Nsg.delete(usuariosNsg);
        }else {
            Util.mensagem("Exclusão cancelada");
        }

        Util.limparCampos(jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtApelido_Nsg, jFmtCpf_Nsg, jFmtNascimento_Nsg, jCboNivel_Nsg, jChbAtivo_Nsg, jPswSenha_Nsg);
    }//GEN-LAST:event_jBtnExcluir_NsgActionPerformed

    private void jFmtCpf_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtCpf_NsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtCpf_NsgActionPerformed

    private void jBtnConfirmar_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmar_NsgActionPerformed
        // TODO add your handling code here:
        UsuariosNsg usuariosNsg = viewBean();
        Usuarios_DAO_Nsg usuarios_DAO_Nsg = new Usuarios_DAO_Nsg();
        
        if (incluindo == true) {
            usuarios_DAO_Nsg.insert(usuariosNsg);
        } else {
            usuarios_DAO_Nsg.update(usuariosNsg);
        }
        
        Util.habilitar(false, jBtnAlterar_Nsg, jBtnExcluir_Nsg, jBtnConfirmar_Nsg, jBtnCancelar_Nsg, jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtApelido_Nsg, jFmtCpf_Nsg, jFmtNascimento_Nsg, jCboNivel_Nsg, jChbAtivo_Nsg, jPswSenha_Nsg);
        Util.habilitar(true, jBtnIncluir_Nsg, jBtnPesquisar_Nsg);
        Util.limparCampos(jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtApelido_Nsg, jFmtCpf_Nsg, jFmtNascimento_Nsg, jCboNivel_Nsg, jChbAtivo_Nsg, jPswSenha_Nsg);
    }//GEN-LAST:event_jBtnConfirmar_NsgActionPerformed

    private void jFmtNascimento_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtNascimento_NsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtNascimento_NsgActionPerformed

    private void jBtnCancelar_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelar_NsgActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jBtnAlterar_Nsg, jBtnExcluir_Nsg, jBtnConfirmar_Nsg, jBtnCancelar_Nsg, jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtApelido_Nsg, jFmtCpf_Nsg, jFmtNascimento_Nsg, jCboNivel_Nsg, jChbAtivo_Nsg, jPswSenha_Nsg);
        Util.habilitar(true, jBtnIncluir_Nsg, jBtnPesquisar_Nsg);
        
        Util.limparCampos(jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtApelido_Nsg, jFmtCpf_Nsg, jFmtNascimento_Nsg, jCboNivel_Nsg, jChbAtivo_Nsg, jPswSenha_Nsg);
        Util.mensagem("Operação cancelada");
    }//GEN-LAST:event_jBtnCancelar_NsgActionPerformed

    private void jBtnPesquisar_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisar_NsgActionPerformed
        // TODO add your handling code here:
        JDlgUsuariosPesquisaNsg jDlgUsuariosPesquisaNsg = new JDlgUsuariosPesquisaNsg(null, true);
        jDlgUsuariosPesquisaNsg.setTelaAnterior(this);
        jDlgUsuariosPesquisaNsg.setVisible(true);
        
        Util.habilitar(true,  jBtnAlterar_Nsg, jBtnPesquisar_Nsg, jBtnCancelar_Nsg,jBtnExcluir_Nsg);
        Util.habilitar(false, jBtnIncluir_Nsg, jBtnConfirmar_Nsg);
    }//GEN-LAST:event_jBtnPesquisar_NsgActionPerformed

    private void jBtnIncluir_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluir_NsgActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jBtnConfirmar_Nsg, jBtnCancelar_Nsg, jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtApelido_Nsg, jFmtCpf_Nsg, jFmtNascimento_Nsg, jCboNivel_Nsg, jChbAtivo_Nsg, jPswSenha_Nsg);
        Util.habilitar(false, jBtnIncluir_Nsg, jBtnAlterar_Nsg, jBtnExcluir_Nsg, jBtnPesquisar_Nsg);
        Util.limparCampos(jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtApelido_Nsg, jFmtCpf_Nsg, jFmtNascimento_Nsg, jCboNivel_Nsg, jChbAtivo_Nsg, jPswSenha_Nsg);
        incluindo = true;
    }//GEN-LAST:event_jBtnIncluir_NsgActionPerformed

    private void jBtnAlterar_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterar_NsgActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jBtnConfirmar_Nsg, jBtnCancelar_Nsg, jTxtCodigo_Nsg, jTxtNome_Nsg, jTxtApelido_Nsg, jFmtCpf_Nsg, jFmtNascimento_Nsg, jCboNivel_Nsg, jChbAtivo_Nsg, jPswSenha_Nsg);
        Util.habilitar(false, jBtnIncluir_Nsg, jBtnAlterar_Nsg, jBtnExcluir_Nsg, jBtnPesquisar_Nsg);
        
        incluindo = false;
    }//GEN-LAST:event_jBtnAlterar_NsgActionPerformed

    private void jCboNivel_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboNivel_NsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboNivel_NsgActionPerformed

    private void jChbAtivo_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChbAtivo_NsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChbAtivo_NsgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuariosNsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuariosNsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuariosNsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuariosNsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgUsuariosNsg dialog = new JDlgUsuariosNsg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar_Nsg;
    private javax.swing.JButton jBtnCancelar_Nsg;
    private javax.swing.JButton jBtnConfirmar_Nsg;
    private javax.swing.JButton jBtnExcluir_Nsg;
    private javax.swing.JButton jBtnIncluir_Nsg;
    private javax.swing.JButton jBtnPesquisar_Nsg;
    private javax.swing.JComboBox<String> jCboNivel_Nsg;
    private javax.swing.JCheckBox jChbAtivo_Nsg;
    private javax.swing.JFormattedTextField jFmtCpf_Nsg;
    private javax.swing.JFormattedTextField jFmtNascimento_Nsg;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPswSenha_Nsg;
    private javax.swing.JTextField jTxtApelido_Nsg;
    private javax.swing.JTextField jTxtCodigo_Nsg;
    private javax.swing.JTextField jTxtNome_Nsg;
    // End of variables declaration//GEN-END:variables
}
