/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import query.JDlgConsultaClienteNsg;
import query.JDlgConsultaProdutoNsg;
import query.JDlgConsultaUsuariosNsg;
import query.JDlgConsultaVendaNsg;
import query.JDlgConsultaVendedorNsg;

/**
 *
 * @author u09229145165
 */
public class JFrmPrincipalNsg extends javax.swing.JFrame {
    

    /**
     * Creates new form JFrmPrincipalNsg
     */
    public JFrmPrincipalNsg() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Menu");
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jBtnToolBarCliente_Nsg = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jBtnToolBarProduto_Nsg = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jBtnToolBarUsuario_Nsg = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jBtnToolBarVendedor_Nsg = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jBtnToolBarVenda_Nsg = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMnuClienteNsg = new javax.swing.JMenuItem();
        jMnuProdutoNsg = new javax.swing.JMenuItem();
        jMnuUsuariosNsg = new javax.swing.JMenuItem();
        jMnuVendedorNsg = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMnuVendaNsg = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator1);

        jBtnToolBarCliente_Nsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/08 - usuario.png"))); // NOI18N
        jBtnToolBarCliente_Nsg.setFocusable(false);
        jBtnToolBarCliente_Nsg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnToolBarCliente_Nsg.setMaximumSize(new java.awt.Dimension(60, 45));
        jBtnToolBarCliente_Nsg.setMinimumSize(new java.awt.Dimension(60, 45));
        jBtnToolBarCliente_Nsg.setPreferredSize(new java.awt.Dimension(60, 45));
        jBtnToolBarCliente_Nsg.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnToolBarCliente_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnToolBarCliente_NsgActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnToolBarCliente_Nsg);
        jToolBar1.add(jSeparator2);

        jBtnToolBarProduto_Nsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/09 - cliente.png"))); // NOI18N
        jBtnToolBarProduto_Nsg.setFocusable(false);
        jBtnToolBarProduto_Nsg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnToolBarProduto_Nsg.setMaximumSize(new java.awt.Dimension(60, 45));
        jBtnToolBarProduto_Nsg.setMinimumSize(new java.awt.Dimension(60, 45));
        jBtnToolBarProduto_Nsg.setPreferredSize(new java.awt.Dimension(60, 45));
        jBtnToolBarProduto_Nsg.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnToolBarProduto_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnToolBarProduto_NsgActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnToolBarProduto_Nsg);
        jToolBar1.add(jSeparator3);

        jBtnToolBarUsuario_Nsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/12 - caixa.png"))); // NOI18N
        jBtnToolBarUsuario_Nsg.setFocusable(false);
        jBtnToolBarUsuario_Nsg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnToolBarUsuario_Nsg.setMaximumSize(new java.awt.Dimension(60, 45));
        jBtnToolBarUsuario_Nsg.setMinimumSize(new java.awt.Dimension(60, 45));
        jBtnToolBarUsuario_Nsg.setPreferredSize(new java.awt.Dimension(60, 45));
        jBtnToolBarUsuario_Nsg.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnToolBarUsuario_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnToolBarUsuario_NsgActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnToolBarUsuario_Nsg);
        jToolBar1.add(jSeparator4);

        jBtnToolBarVendedor_Nsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/14 - compra.png"))); // NOI18N
        jBtnToolBarVendedor_Nsg.setFocusable(false);
        jBtnToolBarVendedor_Nsg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnToolBarVendedor_Nsg.setMaximumSize(new java.awt.Dimension(60, 45));
        jBtnToolBarVendedor_Nsg.setMinimumSize(new java.awt.Dimension(60, 45));
        jBtnToolBarVendedor_Nsg.setPreferredSize(new java.awt.Dimension(60, 45));
        jBtnToolBarVendedor_Nsg.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnToolBarVendedor_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnToolBarVendedor_NsgActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnToolBarVendedor_Nsg);
        jToolBar1.add(jSeparator5);

        jBtnToolBarVenda_Nsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/13 - venda.png"))); // NOI18N
        jBtnToolBarVenda_Nsg.setFocusable(false);
        jBtnToolBarVenda_Nsg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnToolBarVenda_Nsg.setMaximumSize(new java.awt.Dimension(60, 45));
        jBtnToolBarVenda_Nsg.setMinimumSize(new java.awt.Dimension(60, 45));
        jBtnToolBarVenda_Nsg.setPreferredSize(new java.awt.Dimension(60, 45));
        jBtnToolBarVenda_Nsg.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnToolBarVenda_Nsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnToolBarVenda_NsgActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnToolBarVenda_Nsg);
        jToolBar1.add(jSeparator6);

        jMenu1.setText("Cadastro");

        jMnuClienteNsg.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMnuClienteNsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/09 - cliente.png"))); // NOI18N
        jMnuClienteNsg.setText("Cliente");
        jMnuClienteNsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuClienteNsgActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuClienteNsg);

        jMnuProdutoNsg.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMnuProdutoNsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/14 - compra.png"))); // NOI18N
        jMnuProdutoNsg.setText("Produto");
        jMnuProdutoNsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuProdutoNsgActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuProdutoNsg);

        jMnuUsuariosNsg.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuariosNsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/08 - usuario.png"))); // NOI18N
        jMnuUsuariosNsg.setText("Usuarios");
        jMnuUsuariosNsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuariosNsgActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuUsuariosNsg);

        jMnuVendedorNsg.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendedorNsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/13 - venda.png"))); // NOI18N
        jMnuVendedorNsg.setText("Vendedor");
        jMnuVendedorNsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendedorNsgActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuVendedorNsg);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Movimento");

        jMnuVendaNsg.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendaNsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/12 - caixa.png"))); // NOI18N
        jMnuVendaNsg.setText("Venda");
        jMnuVendaNsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendaNsgActionPerformed(evt);
            }
        });
        jMenu2.add(jMnuVendaNsg);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Consultas");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/09 - cliente.png"))); // NOI18N
        jMenuItem1.setText("Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/14 - compra.png"))); // NOI18N
        jMenuItem2.setText("Produto");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/08 - usuario.png"))); // NOI18N
        jMenuItem3.setText("Usuarios");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/13 - venda.png"))); // NOI18N
        jMenuItem4.setText("Vendedor");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/12 - caixa.png"))); // NOI18N
        jMenuItem5.setText("Venda");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 242, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuClienteNsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuClienteNsgActionPerformed
        // TODO add your handling code here:
        JDlgClienteNsg jDlgClienteNsg = new JDlgClienteNsg(null, true);
        jDlgClienteNsg.setVisible(true);
    }//GEN-LAST:event_jMnuClienteNsgActionPerformed

    private void jMnuUsuariosNsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuariosNsgActionPerformed
        // TODO add your handling code here:
        JDlgUsuariosNsg jDlgUsuariosNsg = new JDlgUsuariosNsg(null, true);
        jDlgUsuariosNsg.setVisible(true);
    }//GEN-LAST:event_jMnuUsuariosNsgActionPerformed

    private void jMnuVendaNsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendaNsgActionPerformed
        // TODO add your handling code here:
        JDlgVendaNsg jDlgVendaNsg = new JDlgVendaNsg(null, true);
        jDlgVendaNsg.setVisible(true);
    }//GEN-LAST:event_jMnuVendaNsgActionPerformed

    private void jMnuVendedorNsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendedorNsgActionPerformed
        // TODO add your handling code here:
        JDlgVendedorNsg jDlgVendedorNsg = new JDlgVendedorNsg(null, true);
        jDlgVendedorNsg.setVisible(true);
    }//GEN-LAST:event_jMnuVendedorNsgActionPerformed

    private void jMnuProdutoNsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuProdutoNsgActionPerformed
        // TODO add your handling code here:
        JDlgProdutoNsg jDlgProdutoNsg = new JDlgProdutoNsg(null, true);
        jDlgProdutoNsg.setVisible(true);
    }//GEN-LAST:event_jMnuProdutoNsgActionPerformed

    private void jBtnToolBarCliente_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnToolBarCliente_NsgActionPerformed
        // TODO add your handling code here:
        JDlgUsuariosNsg jDlgUsuariosNsg = new JDlgUsuariosNsg(null, true);
        jDlgUsuariosNsg.setVisible(true);
    }//GEN-LAST:event_jBtnToolBarCliente_NsgActionPerformed

    private void jBtnToolBarProduto_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnToolBarProduto_NsgActionPerformed
        // TODO add your handling code here:
        JDlgConsultaUsuariosNsg jDlgConsultaUsuariosNsg = new JDlgConsultaUsuariosNsg(null, true);
        jDlgConsultaUsuariosNsg.setVisible(true);
    }//GEN-LAST:event_jBtnToolBarProduto_NsgActionPerformed

    private void jBtnToolBarUsuario_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnToolBarUsuario_NsgActionPerformed
        // TODO add your handling code here:
        JDlgVendaNsg jDlgVendaNsg = new JDlgVendaNsg(null, true);
        jDlgVendaNsg.setVisible(true);
    }//GEN-LAST:event_jBtnToolBarUsuario_NsgActionPerformed

    private void jBtnToolBarVendedor_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnToolBarVendedor_NsgActionPerformed
        // TODO add your handling code here:
        JDlgConsultaVendaNsg jDlgConsultaVendaNsg = new JDlgConsultaVendaNsg(null, true);
        jDlgConsultaVendaNsg.setVisible(true);
    }//GEN-LAST:event_jBtnToolBarVendedor_NsgActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JDlgConsultaUsuariosNsg jDlgConsultaUsuariosNsg = new JDlgConsultaUsuariosNsg(null, true);
        jDlgConsultaUsuariosNsg.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JDlgConsultaClienteNsg jDlgConsultaClienteNsg = new JDlgConsultaClienteNsg(null, true);
        jDlgConsultaClienteNsg.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JDlgConsultaProdutoNsg jDlgConsultaProdutoNsg = new JDlgConsultaProdutoNsg(null, true);
        jDlgConsultaProdutoNsg.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JDlgConsultaVendedorNsg jDlgConsultaVendedorNsg = new JDlgConsultaVendedorNsg(null, true);
        jDlgConsultaVendedorNsg.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        JDlgConsultaVendaNsg jDlgConsultaVendaNsg = new JDlgConsultaVendaNsg(null, true);
        jDlgConsultaVendaNsg.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jBtnToolBarVenda_NsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnToolBarVenda_NsgActionPerformed
        // TODO add your handling code here:
        JDlgConsultaVendedorNsg jDlgConsultaVendedorNsg = new JDlgConsultaVendedorNsg(null, true);
        jDlgConsultaVendedorNsg.setVisible(true);
    }//GEN-LAST:event_jBtnToolBarVenda_NsgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipalNsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipalNsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipalNsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipalNsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmPrincipalNsg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnToolBarCliente_Nsg;
    private javax.swing.JButton jBtnToolBarProduto_Nsg;
    private javax.swing.JButton jBtnToolBarUsuario_Nsg;
    private javax.swing.JButton jBtnToolBarVenda_Nsg;
    private javax.swing.JButton jBtnToolBarVendedor_Nsg;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMnuClienteNsg;
    private javax.swing.JMenuItem jMnuProdutoNsg;
    private javax.swing.JMenuItem jMnuUsuariosNsg;
    private javax.swing.JMenuItem jMnuVendaNsg;
    private javax.swing.JMenuItem jMnuVendedorNsg;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
