package bean;
// Generated 13/11/2023 15:15:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProdutoNsg generated by hbm2java
 */
@Entity
@Table(name="produto_nsg"
//    ,catalog="db_nayara_silva"
    ,catalog="test"
)
public class ProdutoNsg  implements java.io.Serializable {


     private int idProdutoNsg;
     private String valorUnitNsg;
     private int saborNsg;
     private String unidadeNsg;
     private int massaNsg;
     private int modoNsg;
     private int tamanhoNsg;
     private String retirarNsg;

    public ProdutoNsg() {
    }

	
    public ProdutoNsg(int idProdutoNsg, String valorUnitNsg, int saborNsg, String unidadeNsg, int massaNsg, int modoNsg, int tamanhoNsg, String retirarNsg) {
        this.idProdutoNsg = idProdutoNsg;
        this.valorUnitNsg = valorUnitNsg;
        this.saborNsg = saborNsg;
        this.unidadeNsg = unidadeNsg;
        this.massaNsg = massaNsg;
        this.modoNsg = modoNsg;
        this.tamanhoNsg = tamanhoNsg;
        this.retirarNsg = retirarNsg;
    }
   
     @Id 

    
    @Column(name="id_produto_nsg", unique=true, nullable=false)
    public int getIdProdutoNsg() {
        return this.idProdutoNsg;
    }
    
    public void setIdProdutoNsg(int idProdutoNsg) {
        this.idProdutoNsg = idProdutoNsg;
    }

    
    @Column(name="valor_unit_nsg", nullable=false, length=80)
    public String getValorUnitNsg() {
        return this.valorUnitNsg;
    }
    
    public void setValorUnitNsg(String valorUnitNsg) {
        this.valorUnitNsg = valorUnitNsg;
    }

    
    @Column(name="sabor_nsg", nullable=false)
    public int getSaborNsg() {
        return this.saborNsg;
    }
    
    public void setSaborNsg(int saborNsg) {
        this.saborNsg = saborNsg;
    }

    
    @Column(name="unidade_nsg", nullable=false, length=80)
    public String getUnidadeNsg() {
        return this.unidadeNsg;
    }
    
    public void setUnidadeNsg(String unidadeNsg) {
        this.unidadeNsg = unidadeNsg;
    }

    
    @Column(name="massa_nsg", nullable=false)
    public int getMassaNsg() {
        return this.massaNsg;
    }
    
    public void setMassaNsg(int massaNsg) {
        this.massaNsg = massaNsg;
    }

    
    @Column(name="modo_nsg", nullable=false)
    public int getModoNsg() {
        return this.modoNsg;
    }
    
    public void setModoNsg(int modoNsg) {
        this.modoNsg = modoNsg;
    }

    
    @Column(name="tamanho_nsg", nullable=false)
    public int getTamanhoNsg() {
        return this.tamanhoNsg;
    }
    
    public void setTamanhoNsg(int tamanhoNsg) {
        this.tamanhoNsg = tamanhoNsg;
    }

    
    @Column(name="retirar_nsg", nullable=false, length=80)
    public String getRetirarNsg() {
        return this.retirarNsg;
    }
    
    public void setRetirarNsg(String retirarNsg) {
        this.retirarNsg = retirarNsg;
    }
}


