package bean;
// Generated 13/11/2023 15:15:33 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VendaProdutoNsg generated by hbm2java
 */
@Entity
@Table(name="vendaProduto_nsg"
    ,catalog="db_nayara_silva"
//    ,catalog="test"
)
public class VendaProdutoNsg  implements java.io.Serializable {


     private int idVendaProdutoNsg;
     private ProdutoNsg produtoNsg;
     private VendaNsg vendaNsg;
     private String quantidadeNsg;
     private String valorUnitNsg;

    public VendaProdutoNsg() {
    }

    public VendaProdutoNsg(int idVendaProdutoNsg, ProdutoNsg produtoNsg, VendaNsg vendaNsg, String quantidadeNsg, String valorUnitNsg) {
       this.idVendaProdutoNsg = idVendaProdutoNsg;
       this.produtoNsg = produtoNsg;
       this.vendaNsg = vendaNsg;
       this.quantidadeNsg = quantidadeNsg;
       this.valorUnitNsg = valorUnitNsg;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_vendaProduto_nsg", unique=true, nullable=false)
    public int getIdVendaProdutoNsg() {
        return this.idVendaProdutoNsg;
    }
    
    public void setIdVendaProdutoNsg(int idVendaProdutoNsg) {
        this.idVendaProdutoNsg = idVendaProdutoNsg;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produto_nsg", nullable=false)
    public ProdutoNsg getProdutoNsg() {
        return this.produtoNsg;
    }
    
    public void setProdutoNsg(ProdutoNsg produtoNsg) {
        this.produtoNsg = produtoNsg;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="venda_nsg", nullable=false)
    public VendaNsg getVendaNsg() {
        return this.vendaNsg;
    }
    
    public void setVendaNsg(VendaNsg vendaNsg) {
        this.vendaNsg = vendaNsg;
    }
    @Column(name="quantidade_nsg", nullable=false, length=80)
    public String getQuantidadeNsg() {
        return this.quantidadeNsg;
    }
    
    public void setQuantidadeNsg(String quantidadeNsg) {
        this.quantidadeNsg = quantidadeNsg;
    }

    
    @Column(name="valor_unit_nsg", nullable=false, length=80)
    public String getValorUnitNsg() {
        return this.valorUnitNsg;
    }
    
    public void setValorUnitNsg(String valorUnitNsg) {
        this.valorUnitNsg = valorUnitNsg;
    }
}


