package bean;
// Generated 13/11/2023 15:15:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VendedorNsg generated by hbm2java
 */
@Entity
@Table(name="vendedor_nsg"
    ,catalog="db_nayara_silva"
//    ,catalog="test"
)
public class VendedorNsg  implements java.io.Serializable {


     private int idVendedorNsg;
     private String nomeNsg;
     private String cpfNsg;
     private String celularNsg;
     private int comissaoNsg;
     private int generoNsg;

    public VendedorNsg() {
    }

	
    public VendedorNsg(int idVendedorNsg, String nomeNsg, String cpfNsg, String celularNsg, int comissaoNsg, int generoNsg) {
        this.idVendedorNsg = idVendedorNsg;
        this.nomeNsg = nomeNsg;
        this.cpfNsg = cpfNsg;
        this.celularNsg = celularNsg;
        this.comissaoNsg = comissaoNsg;
        this.generoNsg = generoNsg;
    }
   
     @Id 

    
    @Column(name="id_vendedor_nsg", unique=true, nullable=false)
    public int getIdVendedorNsg() {
        return this.idVendedorNsg;
    }
    
    public void setIdVendedorNsg(int idVendedorNsg) {
        this.idVendedorNsg = idVendedorNsg;
    }

    
    @Column(name="nome_nsg", nullable=false, length=80)
    public String getNomeNsg() {
        return this.nomeNsg;
    }
    
    public void setNomeNsg(String nomeNsg) {
        this.nomeNsg = nomeNsg;
    }

    
    @Column(name="cpf_nsg", nullable=false, length=80)
    public String getCpfNsg() {
        return this.cpfNsg;
    }
    
    public void setCpfNsg(String cpfNsg) {
        this.cpfNsg = cpfNsg;
    }

    
    @Column(name="celular_nsg", nullable=false, length=80)
    public String getCelularNsg() {
        return this.celularNsg;
    }
    
    public void setCelularNsg(String celularNsg) {
        this.celularNsg = celularNsg;
    }
    
    @Column(name="comissao_nsg", nullable=false)
    public int getComissaoNsg() {
        return this.comissaoNsg;
    }
    
    public void setComissaoNsg(int comissaoNsg) {
        this.comissaoNsg = comissaoNsg;
    }
    
    @Column(name="genero_nsg", nullable=false)
    public int getGeneroNsg() {
        return this.generoNsg;
    }
    
    public void setGeneroNsg(int generoNsg) {
        this.generoNsg = generoNsg;
    }
    
    @Override
    public String toString() {
        return getNomeNsg();
    }

    public boolean equals (Object object) {
    if (object instanceof VendedorNsg) {
        VendedorNsg vendedorNsg = (VendedorNsg) object;
        
        if (this.getIdVendedorNsg() == vendedorNsg.getIdVendedorNsg()){
            return true;
        }
    }
    return false;
    }
}


